(ns photonic_switch.actor
  "photonic_switch clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). Optical circuit switch / 光電融合 routing fabric.

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; SwitchFabric
   {:db/ident :photonic_switch.SwitchFabric/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :photonic_switch.SwitchFabric/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.SwitchFabric/radix :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.SwitchFabric/technology :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.SwitchFabric/switchingTimeNs :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.SwitchFabric/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.SwitchFabric/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; OpticalPort
   {:db/ident :photonic_switch.OpticalPort/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :photonic_switch.OpticalPort/fabricId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.OpticalPort/index :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.OpticalPort/direction :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.OpticalPort/lambdaNm :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.OpticalPort/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.OpticalPort/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; WaveguideCross
   {:db/ident :photonic_switch.WaveguideCross/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :photonic_switch.WaveguideCross/fabricId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.WaveguideCross/row :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.WaveguideCross/column :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.WaveguideCross/state :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.WaveguideCross/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.WaveguideCross/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; MemsMirror
   {:db/ident :photonic_switch.MemsMirror/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :photonic_switch.MemsMirror/fabricId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.MemsMirror/tiltDeg :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.MemsMirror/settleTimeMs :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.MemsMirror/status :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.MemsMirror/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.MemsMirror/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; RoutePath
   {:db/ident :photonic_switch.RoutePath/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :photonic_switch.RoutePath/fabricId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.RoutePath/ingressPort :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.RoutePath/egressPort :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.RoutePath/hops :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.RoutePath/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.RoutePath/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; LossBudget
   {:db/ident :photonic_switch.LossBudget/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :photonic_switch.LossBudget/fabricId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.LossBudget/insertionLossDb :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.LossBudget/crosstalkDb :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.LossBudget/marginDb :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.LossBudget/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :photonic_switch.LossBudget/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"SwitchFabric" "OpticalPort" "WaveguideCross" "MemsMirror" "RoutePath" "LossBudget"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "photonic_switch: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "photonic_switch: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "photonic_switch: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── SwitchFabric ────────────────────────────────────────────────────────────────
(defn create-switch-fabric
  "Create a SwitchFabric."
  [port data]
  (require-fields data ["name" "radix"])
  (let [id (new-id "psw_swi")
        e {:db/id id
           :photonic_switch.SwitchFabric/id id
           :photonic_switch.SwitchFabric/name (get data :name)
           :photonic_switch.SwitchFabric/radix (as-long (get data :radix))
           :photonic_switch.SwitchFabric/technology (get data :technology)
           :photonic_switch.SwitchFabric/switchingTimeNs (as-double (get data :switchingTimeNs))
           :photonic_switch.SwitchFabric/createdAt (now)
           :photonic_switch.SwitchFabric/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-switch-fabrics
  "List SwitchFabric with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-switch-fabrics port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :photonic_switch.SwitchFabric/id))
         rows (apply-filters rows (:filter opts) [:photonic_switch.SwitchFabric/name :photonic_switch.SwitchFabric/radix :photonic_switch.SwitchFabric/technology :photonic_switch.SwitchFabric/switchingTimeNs])]
     (paginate rows opts))))

(defn get-switch-fabric
  "Retrieve a SwitchFabric by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-switch-fabric port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-switch-fabric
  "Update a SwitchFabric; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :photonic_switch.SwitchFabric/name (get data :name)]))
                   (cond-> (contains? data :radix) (conj [:db/add id :photonic_switch.SwitchFabric/radix (as-long (get data :radix))]))
                   (cond-> (contains? data :technology) (conj [:db/add id :photonic_switch.SwitchFabric/technology (get data :technology)]))
                   (cond-> (contains? data :switchingTimeNs) (conj [:db/add id :photonic_switch.SwitchFabric/switchingTimeNs (as-double (get data :switchingTimeNs))]))
                   (conj [:db/add id :photonic_switch.SwitchFabric/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-switch-fabric
  "Delete a SwitchFabric."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── OpticalPort ────────────────────────────────────────────────────────────────
(defn create-optical-port
  "Create a OpticalPort."
  [port data]
  (require-fields data ["index" "direction"])
  (let [id (new-id "psw_opt")
        e {:db/id id
           :photonic_switch.OpticalPort/id id
           :photonic_switch.OpticalPort/fabricId (get data :fabricId)
           :photonic_switch.OpticalPort/index (as-long (get data :index))
           :photonic_switch.OpticalPort/direction (get data :direction)
           :photonic_switch.OpticalPort/lambdaNm (as-double (get data :lambdaNm))
           :photonic_switch.OpticalPort/createdAt (now)
           :photonic_switch.OpticalPort/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-optical-ports
  "List OpticalPort with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-optical-ports port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :photonic_switch.OpticalPort/id))
         rows (apply-filters rows (:filter opts) [:photonic_switch.OpticalPort/fabricId :photonic_switch.OpticalPort/index :photonic_switch.OpticalPort/direction :photonic_switch.OpticalPort/lambdaNm])]
     (paginate rows opts))))

(defn get-optical-port
  "Retrieve a OpticalPort by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-optical-port port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-optical-port
  "Update a OpticalPort; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :fabricId) (conj [:db/add id :photonic_switch.OpticalPort/fabricId (get data :fabricId)]))
                   (cond-> (contains? data :index) (conj [:db/add id :photonic_switch.OpticalPort/index (as-long (get data :index))]))
                   (cond-> (contains? data :direction) (conj [:db/add id :photonic_switch.OpticalPort/direction (get data :direction)]))
                   (cond-> (contains? data :lambdaNm) (conj [:db/add id :photonic_switch.OpticalPort/lambdaNm (as-double (get data :lambdaNm))]))
                   (conj [:db/add id :photonic_switch.OpticalPort/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-optical-port
  "Delete a OpticalPort."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── WaveguideCross ────────────────────────────────────────────────────────────────
(defn create-waveguide-cross
  "Create a WaveguideCross."
  [port data]
  (require-fields data ["row" "column"])
  (let [id (new-id "psw_wav")
        e {:db/id id
           :photonic_switch.WaveguideCross/id id
           :photonic_switch.WaveguideCross/fabricId (get data :fabricId)
           :photonic_switch.WaveguideCross/row (as-long (get data :row))
           :photonic_switch.WaveguideCross/column (as-long (get data :column))
           :photonic_switch.WaveguideCross/state (get data :state)
           :photonic_switch.WaveguideCross/createdAt (now)
           :photonic_switch.WaveguideCross/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-waveguide-crosses
  "List WaveguideCross with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-waveguide-crosses port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :photonic_switch.WaveguideCross/id))
         rows (apply-filters rows (:filter opts) [:photonic_switch.WaveguideCross/fabricId :photonic_switch.WaveguideCross/row :photonic_switch.WaveguideCross/column :photonic_switch.WaveguideCross/state])]
     (paginate rows opts))))

(defn get-waveguide-cross
  "Retrieve a WaveguideCross by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-waveguide-cross port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-waveguide-cross
  "Update a WaveguideCross; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :fabricId) (conj [:db/add id :photonic_switch.WaveguideCross/fabricId (get data :fabricId)]))
                   (cond-> (contains? data :row) (conj [:db/add id :photonic_switch.WaveguideCross/row (as-long (get data :row))]))
                   (cond-> (contains? data :column) (conj [:db/add id :photonic_switch.WaveguideCross/column (as-long (get data :column))]))
                   (cond-> (contains? data :state) (conj [:db/add id :photonic_switch.WaveguideCross/state (get data :state)]))
                   (conj [:db/add id :photonic_switch.WaveguideCross/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-waveguide-cross
  "Delete a WaveguideCross."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── MemsMirror ────────────────────────────────────────────────────────────────
(defn create-mems-mirror
  "Create a MemsMirror."
  [port data]
  (require-fields data ["tiltDeg" "settleTimeMs"])
  (let [id (new-id "psw_mem")
        e {:db/id id
           :photonic_switch.MemsMirror/id id
           :photonic_switch.MemsMirror/fabricId (get data :fabricId)
           :photonic_switch.MemsMirror/tiltDeg (as-double (get data :tiltDeg))
           :photonic_switch.MemsMirror/settleTimeMs (as-double (get data :settleTimeMs))
           :photonic_switch.MemsMirror/status (get data :status)
           :photonic_switch.MemsMirror/createdAt (now)
           :photonic_switch.MemsMirror/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-mems-mirrors
  "List MemsMirror with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-mems-mirrors port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :photonic_switch.MemsMirror/id))
         rows (apply-filters rows (:filter opts) [:photonic_switch.MemsMirror/fabricId :photonic_switch.MemsMirror/tiltDeg :photonic_switch.MemsMirror/settleTimeMs :photonic_switch.MemsMirror/status])]
     (paginate rows opts))))

(defn get-mems-mirror
  "Retrieve a MemsMirror by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-mems-mirror port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-mems-mirror
  "Update a MemsMirror; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :fabricId) (conj [:db/add id :photonic_switch.MemsMirror/fabricId (get data :fabricId)]))
                   (cond-> (contains? data :tiltDeg) (conj [:db/add id :photonic_switch.MemsMirror/tiltDeg (as-double (get data :tiltDeg))]))
                   (cond-> (contains? data :settleTimeMs) (conj [:db/add id :photonic_switch.MemsMirror/settleTimeMs (as-double (get data :settleTimeMs))]))
                   (cond-> (contains? data :status) (conj [:db/add id :photonic_switch.MemsMirror/status (get data :status)]))
                   (conj [:db/add id :photonic_switch.MemsMirror/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-mems-mirror
  "Delete a MemsMirror."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── RoutePath ────────────────────────────────────────────────────────────────
(defn create-route-path
  "Create a RoutePath."
  [port data]
  (require-fields data ["ingressPort" "egressPort"])
  (let [id (new-id "psw_rou")
        e {:db/id id
           :photonic_switch.RoutePath/id id
           :photonic_switch.RoutePath/fabricId (get data :fabricId)
           :photonic_switch.RoutePath/ingressPort (get data :ingressPort)
           :photonic_switch.RoutePath/egressPort (get data :egressPort)
           :photonic_switch.RoutePath/hops (as-long (get data :hops))
           :photonic_switch.RoutePath/createdAt (now)
           :photonic_switch.RoutePath/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-route-paths
  "List RoutePath with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-route-paths port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :photonic_switch.RoutePath/id))
         rows (apply-filters rows (:filter opts) [:photonic_switch.RoutePath/fabricId :photonic_switch.RoutePath/ingressPort :photonic_switch.RoutePath/egressPort :photonic_switch.RoutePath/hops])]
     (paginate rows opts))))

(defn get-route-path
  "Retrieve a RoutePath by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-route-path port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-route-path
  "Update a RoutePath; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :fabricId) (conj [:db/add id :photonic_switch.RoutePath/fabricId (get data :fabricId)]))
                   (cond-> (contains? data :ingressPort) (conj [:db/add id :photonic_switch.RoutePath/ingressPort (get data :ingressPort)]))
                   (cond-> (contains? data :egressPort) (conj [:db/add id :photonic_switch.RoutePath/egressPort (get data :egressPort)]))
                   (cond-> (contains? data :hops) (conj [:db/add id :photonic_switch.RoutePath/hops (as-long (get data :hops))]))
                   (conj [:db/add id :photonic_switch.RoutePath/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-route-path
  "Delete a RoutePath."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── LossBudget ────────────────────────────────────────────────────────────────
(defn create-loss-budget
  "Create a LossBudget."
  [port data]
  (require-fields data ["insertionLossDb" "crosstalkDb"])
  (let [id (new-id "psw_los")
        e {:db/id id
           :photonic_switch.LossBudget/id id
           :photonic_switch.LossBudget/fabricId (get data :fabricId)
           :photonic_switch.LossBudget/insertionLossDb (as-double (get data :insertionLossDb))
           :photonic_switch.LossBudget/crosstalkDb (as-double (get data :crosstalkDb))
           :photonic_switch.LossBudget/marginDb (as-double (get data :marginDb))
           :photonic_switch.LossBudget/createdAt (now)
           :photonic_switch.LossBudget/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-loss-budgets
  "List LossBudget with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-loss-budgets port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :photonic_switch.LossBudget/id))
         rows (apply-filters rows (:filter opts) [:photonic_switch.LossBudget/fabricId :photonic_switch.LossBudget/insertionLossDb :photonic_switch.LossBudget/crosstalkDb :photonic_switch.LossBudget/marginDb])]
     (paginate rows opts))))

(defn get-loss-budget
  "Retrieve a LossBudget by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-loss-budget port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-loss-budget
  "Update a LossBudget; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :fabricId) (conj [:db/add id :photonic_switch.LossBudget/fabricId (get data :fabricId)]))
                   (cond-> (contains? data :insertionLossDb) (conj [:db/add id :photonic_switch.LossBudget/insertionLossDb (as-double (get data :insertionLossDb))]))
                   (cond-> (contains? data :crosstalkDb) (conj [:db/add id :photonic_switch.LossBudget/crosstalkDb (as-double (get data :crosstalkDb))]))
                   (cond-> (contains? data :marginDb) (conj [:db/add id :photonic_switch.LossBudget/marginDb (as-double (get data :marginDb))]))
                   (conj [:db/add id :photonic_switch.LossBudget/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-loss-budget
  "Delete a LossBudget."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/switchfabrics" :op :create :entity "SwitchFabric"}
   {:method "GET" :path "/v1/switchfabrics" :op :list :entity "SwitchFabric"}
   {:method "GET" :path "/v1/switchfabrics/:id" :op :get :entity "SwitchFabric"}
   {:method "PATCH" :path "/v1/switchfabrics/:id" :op :update :entity "SwitchFabric"}
   {:method "DELETE" :path "/v1/switchfabrics/:id" :op :delete :entity "SwitchFabric"}
   {:method "POST" :path "/v1/opticalports" :op :create :entity "OpticalPort"}
   {:method "GET" :path "/v1/opticalports" :op :list :entity "OpticalPort"}
   {:method "GET" :path "/v1/opticalports/:id" :op :get :entity "OpticalPort"}
   {:method "PATCH" :path "/v1/opticalports/:id" :op :update :entity "OpticalPort"}
   {:method "DELETE" :path "/v1/opticalports/:id" :op :delete :entity "OpticalPort"}
   {:method "POST" :path "/v1/waveguidecrosses" :op :create :entity "WaveguideCross"}
   {:method "GET" :path "/v1/waveguidecrosses" :op :list :entity "WaveguideCross"}
   {:method "GET" :path "/v1/waveguidecrosses/:id" :op :get :entity "WaveguideCross"}
   {:method "PATCH" :path "/v1/waveguidecrosses/:id" :op :update :entity "WaveguideCross"}
   {:method "DELETE" :path "/v1/waveguidecrosses/:id" :op :delete :entity "WaveguideCross"}
   {:method "POST" :path "/v1/memsmirrors" :op :create :entity "MemsMirror"}
   {:method "GET" :path "/v1/memsmirrors" :op :list :entity "MemsMirror"}
   {:method "GET" :path "/v1/memsmirrors/:id" :op :get :entity "MemsMirror"}
   {:method "PATCH" :path "/v1/memsmirrors/:id" :op :update :entity "MemsMirror"}
   {:method "DELETE" :path "/v1/memsmirrors/:id" :op :delete :entity "MemsMirror"}
   {:method "POST" :path "/v1/routepaths" :op :create :entity "RoutePath"}
   {:method "GET" :path "/v1/routepaths" :op :list :entity "RoutePath"}
   {:method "GET" :path "/v1/routepaths/:id" :op :get :entity "RoutePath"}
   {:method "PATCH" :path "/v1/routepaths/:id" :op :update :entity "RoutePath"}
   {:method "DELETE" :path "/v1/routepaths/:id" :op :delete :entity "RoutePath"}
   {:method "POST" :path "/v1/lossbudgets" :op :create :entity "LossBudget"}
   {:method "GET" :path "/v1/lossbudgets" :op :list :entity "LossBudget"}
   {:method "GET" :path "/v1/lossbudgets/:id" :op :get :entity "LossBudget"}
   {:method "PATCH" :path "/v1/lossbudgets/:id" :op :update :entity "LossBudget"}
   {:method "DELETE" :path "/v1/lossbudgets/:id" :op :delete :entity "LossBudget"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"switchfabrics" {:create create-switch-fabric :list list-switch-fabrics :get get-switch-fabric :update update-switch-fabric :delete delete-switch-fabric}
   "opticalports" {:create create-optical-port :list list-optical-ports :get get-optical-port :update update-optical-port :delete delete-optical-port}
   "waveguidecrosses" {:create create-waveguide-cross :list list-waveguide-crosses :get get-waveguide-cross :update update-waveguide-cross :delete delete-waveguide-cross}
   "memsmirrors" {:create create-mems-mirror :list list-mems-mirrors :get get-mems-mirror :update update-mems-mirror :delete delete-mems-mirror}
   "routepaths" {:create create-route-path :list list-route-paths :get get-route-path :update update-route-path :delete delete-route-path}
   "lossbudgets" {:create create-loss-budget :list list-loss-budgets :get get-loss-budget :update update-loss-budget :delete delete-loss-budget}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "photonic_switch-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
